# Generated by Django 5.1.6 on 2025-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='title_en',
            field=models.CharField(default='no title', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(default='no title', max_length=255),
        ),
    ]
